//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvtK22CNTLesson11_2210900063.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TvtProduct
    {
        public int TvtId2210900063 { get; set; }
        public string TvtProName { get; set; }
        public Nullable<int> TvtQty { get; set; }
        public Nullable<double> TvtPrice { get; set; }
        public Nullable<int> TvtCateld { get; set; }
        public string TvtActive { get; set; }
    }
}
